package azure_sdk_for_cangjie

// struct Copy {
//     var data = 2012
// }

// class Share {
//     var data = 2012
// }

// main() {
//     let c1 = Copy()
//     var c2 = c1
//     c2.data = 2023
//     println("${c1.data}, ${c2.data}")

//     let s1 = Share()
//     let s2 = s1
//     s2.data = 2023
//     println("${s1.data}, ${s2.data}")
// }

// example.cj
let a = 2023
func b() {}
struct C {}
class D {}
enum E { F | G }

main() {
    println(a)
    println(a)
}